filter:
  excluded_paths:
    - 'tests/'
    - 'vendor/'

build:
  dependencies:
    before:
      - pecl install zip
    override:
      - composer update --no-interaction
  nodes:
    php:
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - command: vendor/bin/phpunit --testdox --verbose --coverage-clover=coverage.clover
            coverage:
              file: coverage.clover
              format: clover
